spring:
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: DEBUG
server:
    port: ${PORT:8080}