spring:
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 275067037620-okntqnsqjlrq5ud3hv0ufq4bn8u461t7.apps.googleusercontent.com
            client-secret: rUN6zZZxOYwx9dD3mTJzonpb
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: DEBUG
